name: GPU tests + code coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


jobs:
  test_coverage:
    runs-on: ParallelHoss

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          coverage run --source=genlm/backend -m pytest --benchmark-disable --ignore=tests/test_mlx.py
          coverage json --omit "*/test*"
          coverage report --omit "*/test*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          slug: genlm/genlm-backend

  test_mlx_coverage:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .[mlx]
          pip install -r requirements-dev.txt

      - name: Run MLX tests
        run: |
          coverage run --source=genlm/backend -m pytest tests/test_mlx.py
          coverage json --omit "*/test*"
          coverage report --omit "*/test*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          slug: genlm/genlm-backend
